(() => {
  const config=window.BEAUTIX_CONFIG;if(!config||!window.supabase)return;
  const client=window.supabase.createClient(config.supabaseUrl,config.supabasePublishableKey);
  const money=v=>new Intl.NumberFormat('he-IL',{style:'currency',currency:'ILS',maximumFractionDigits:0}).format(Number(v||0));
  const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const labels={planned:'מתוכנן',completed:'בוצע',deferred:'נדחה',overdue:'באיחור',cancelled:'בוטל'};let items=[];

  function styles(){let s=document.getElementById('cashflow-actions-style');if(!s){s=document.createElement('style');s.id='cashflow-actions-style';document.head.appendChild(s);}s.textContent=`
  .cashflow-day-add-row{display:flex;justify-content:flex-end;margin:0 0 14px}.cashflow-day-add{display:inline-flex;gap:8px;align-items:center;justify-content:center;min-height:40px;padding:0 15px;border:0;border-radius:12px;background:linear-gradient(135deg,#ef2d9a,#6f42a8);color:#fff;font:inherit;font-weight:800;cursor:pointer}.day-body{gap:18px}.day-body section{min-width:0;padding:16px;border:1px solid #e3e7ef;border-radius:16px;background:#fff}.day-body section h4{margin:0 0 12px;padding-bottom:10px;border-bottom:1px solid #edf0f5;color:#7b3bb0}.day-body section ul{display:grid;gap:10px;margin:0;padding:0;list-style:none}
  .cashflow-entry-item{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center;padding:12px;border:1px solid #e4e8f0;border-radius:14px;background:#fafbfe}.cashflow-entry-item[draggable=true]{cursor:grab}.cashflow-entry-item.dragging{opacity:.45}.cashflow-drop-target{outline:2px dashed #8b4ab5;outline-offset:4px}.cashflow-entry-main strong{display:block;color:#26364a}.cashflow-entry-meta{display:flex;flex-wrap:wrap;gap:6px 10px;margin-top:5px;color:#7f8b9d;font-size:.79rem}.cashflow-entry-amount{font-weight:800;color:#26364a}.cashflow-entry-side{display:flex;align-items:center;gap:7px;flex-wrap:wrap;justify-content:flex-end}.cashflow-status{padding:6px 10px;border-radius:999px;background:#eef1f6;color:#536176;font-size:.74rem;font-weight:800}.cashflow-status-completed{background:#e8f7ef;color:#168455}.cashflow-status-overdue{background:#fdecec;color:#b33a45}.cashflow-status-deferred{background:#fff3d9;color:#9b6a00}.cashflow-mini-btn{padding:7px 10px;border:0;border-radius:9px;background:#fff;color:#7837a9;font:inherit;font-size:.78rem;font-weight:800;cursor:pointer;box-shadow:inset 0 0 0 1px #d8c8e6}.cashflow-mini-btn.primary{background:#7b3bb0;color:#fff;box-shadow:none}.cashflow-menu{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:12px;padding-top:12px;border-top:1px solid #eceff4}.cashflow-menu[hidden]{display:none}
  .cashflow-modal{position:fixed;inset:0;z-index:1200;display:grid;place-items:center;padding:18px;background:rgba(22,18,34,.48);backdrop-filter:blur(5px)}.cashflow-modal[hidden]{display:none}.cashflow-dialog{position:relative;width:min(500px,100%);max-height:calc(100dvh - 24px);overflow:auto;padding:24px;border-radius:22px;background:#fff}.cashflow-dialog h2{margin:0 0 16px;color:#50306f}.cashflow-dialog form{display:grid;gap:13px}.cashflow-dialog label{display:grid;gap:6px;color:#4c596b;font-weight:700}.cashflow-dialog input,.cashflow-dialog select,.cashflow-dialog textarea{width:100%;box-sizing:border-box;padding:11px 12px;border:1px solid #d9deea;border-radius:12px;font:inherit}.cashflow-dialog button[type=submit]{padding:12px;border:0;border-radius:12px;background:linear-gradient(135deg,#ef2d9a,#6f42a8);color:#fff;font-weight:800}.cashflow-close{position:absolute;top:10px;left:12px;border:0;background:transparent;font-size:1.7rem;color:#7b8798}.cashflow-form-status{margin:0;color:#b33a45}
  @media(min-width:760px){.day-body{grid-template-columns:1fr 1fr}.cashflow-day-add-row{grid-column:1/-1}}@media(max-width:620px){.cashflow-entry-item{grid-template-columns:1fr}.cashflow-entry-side{justify-content:space-between}.cashflow-day-add{width:100%}.cashflow-menu{grid-template-columns:1fr}}
  `;}

  function modal(){if(document.getElementById('cashflow-modal'))return;document.body.insertAdjacentHTML('beforeend',`<div id="cashflow-modal" class="cashflow-modal" hidden><section class="cashflow-dialog"><button id="cashflow-close" class="cashflow-close" type="button">×</button><h2 id="cashflow-modal-title">הוספת תנועה</h2><form id="cashflow-form"><input id="cashflow-entry-id" type="hidden"><label>תאריך<input id="cashflow-date" type="date" required></label><label>סוג<select id="cashflow-type"><option value="income">הכנסה</option><option value="expense">הוצאה</option></select></label><label>סכום<input id="cashflow-amount" type="number" min="0.01" step="0.01" required></label><label>תיאור<input id="cashflow-description" maxlength="160" required></label><label id="cashflow-status-wrap">סטטוס<select id="cashflow-status"><option value="planned">מתוכנן</option><option value="completed">בוצע</option><option value="deferred">נדחה</option><option value="overdue">באיחור</option><option value="cancelled">בוטל</option></select></label><label>הערה<textarea id="cashflow-note" rows="3"></textarea></label><button type="submit">שמירה</button><p id="cashflow-form-status" class="cashflow-form-status" hidden></p></form></section></div>`);const m=document.getElementById('cashflow-modal');document.getElementById('cashflow-close').onclick=()=>m.hidden=true;m.onclick=e=>{if(e.target===m)m.hidden=true};document.getElementById('cashflow-form').onsubmit=saveForm;}
  function create(date,type='income'){modal();document.getElementById('cashflow-modal-title').textContent='הוספת תנועה חדשה';document.getElementById('cashflow-entry-id').value='';document.getElementById('cashflow-date').value=date;document.getElementById('cashflow-type').value=type;['cashflow-type','cashflow-amount','cashflow-description'].forEach(id=>document.getElementById(id).disabled=false);document.getElementById('cashflow-amount').value='';document.getElementById('cashflow-description').value='';document.getElementById('cashflow-status-wrap').hidden=true;document.getElementById('cashflow-note').value='';document.getElementById('cashflow-form-status').hidden=true;document.getElementById('cashflow-modal').hidden=false;}
  function edit(id){const x=items.find(i=>i.id===id);if(!x)return;modal();document.getElementById('cashflow-modal-title').textContent='עדכון תנועה';document.getElementById('cashflow-entry-id').value=x.id;document.getElementById('cashflow-date').value=x.date;document.getElementById('cashflow-type').value=x.type;document.getElementById('cashflow-amount').value=x.amount;document.getElementById('cashflow-description').value=x.description;['cashflow-type','cashflow-amount','cashflow-description'].forEach(id=>document.getElementById(id).disabled=true);document.getElementById('cashflow-status-wrap').hidden=false;document.getElementById('cashflow-status').value=x.status||'planned';document.getElementById('cashflow-note').value=x.action_note||'';document.getElementById('cashflow-modal').hidden=false;}
  async function saveForm(e){e.preventDefault();const box=document.getElementById('cashflow-form-status');box.hidden=true;try{const id=document.getElementById('cashflow-entry-id').value;if(id){const{error}=await client.rpc('update_cashflow_entry_action',{p_entry_id:id,p_status:document.getElementById('cashflow-status').value,p_note:document.getElementById('cashflow-note').value||null,p_new_date:document.getElementById('cashflow-date').value});if(error)throw error;}else{const{error}=await client.rpc('create_cashflow_entry',{p_date:document.getElementById('cashflow-date').value,p_type:document.getElementById('cashflow-type').value,p_amount:Number(document.getElementById('cashflow-amount').value),p_description:document.getElementById('cashflow-description').value,p_note:document.getElementById('cashflow-note').value||null});if(error)throw error;}document.getElementById('cashflow-modal').hidden=true;await load();}catch(err){box.textContent=err.message;box.hidden=false;}}

  async function quick(id,action,args={}){try{const{error}=await client.rpc('cashflow_quick_action',{p_entry_id:id,p_action:action,p_target_date:args.date||null,p_reminder_at:args.reminder||null,p_recurrence:args.recurrence||null,p_occurrences:args.count||3});if(error)throw error;await load();}catch(e){alert(`הפעולה נכשלה: ${e.message}`);}}
  function promptAction(id,action){if(action==='move'||action==='duplicate'){const date=prompt('בחר תאריך בפורמט YYYY-MM-DD');if(date)quick(id,action,{date});}else if(action==='reminder'){const reminder=prompt('מועד תזכורת בפורמט YYYY-MM-DD HH:MM');if(reminder)quick(id,action,{reminder:new Date(reminder.replace(' ','T')).toISOString()});}else if(action==='recurring'){const recurrence=prompt('תדירות: daily / weekly / monthly','monthly');if(!recurrence)return;const count=Number(prompt('כמה מופעים? 2–12','3'));quick(id,action,{recurrence,count});}else if(action==='cancel'){if(confirm('לבטל ולהסתיר את התנועה?'))quick(id,action);}else quick(id,action);}

  function entry(x){const reminder=x.reminder_at?`<span>🔔 ${esc(new Date(x.reminder_at).toLocaleString('he-IL'))}</span>`:'';const recurring=x.recurrence?`<span>↻ ${esc(x.recurrence)}</span>`:'';return `<li class="cashflow-entry-item" draggable="true" data-entry-id="${esc(x.id)}"><div class="cashflow-entry-main"><strong>${esc(x.description)}</strong><div class="cashflow-entry-meta"><span class="cashflow-entry-amount">${money(x.amount)}</span>${x.action_note?`<span>${esc(x.action_note)}</span>`:''}${reminder}${recurring}</div><div class="cashflow-menu" id="menu-${esc(x.id)}" hidden><button class="cashflow-mini-btn" data-quick="duplicate">שכפול</button><button class="cashflow-mini-btn" data-quick="recurring">תנועה חוזרת</button><button class="cashflow-mini-btn" data-quick="move">העבר תאריך</button><button class="cashflow-mini-btn" data-quick="tomorrow">דחה למחר</button><button class="cashflow-mini-btn" data-quick="reminder">צור תזכורת</button><button class="cashflow-mini-btn" data-quick="cancel">בטל</button><button class="cashflow-mini-btn" data-edit="${esc(x.id)}">עריכה מלאה</button></div></div><div class="cashflow-entry-side"><span class="cashflow-status cashflow-status-${esc(x.status)}">${esc(labels[x.status]||'מתוכנן')}</span>${x.status!=='completed'?`<button class="cashflow-mini-btn primary" data-quick="complete">סמן בוצע</button>`:''}<button class="cashflow-mini-btn" data-toggle-menu="${esc(x.id)}">פעולות</button></div></li>`;}

  function bind(){document.querySelectorAll('[data-toggle-menu]').forEach(b=>b.onclick=()=>{const m=document.getElementById(`menu-${b.dataset.toggleMenu}`);if(m)m.hidden=!m.hidden});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>{const li=b.closest('[data-entry-id]');if(li)promptAction(li.dataset.entryId,b.dataset.quick)});document.querySelectorAll('[data-entry-id]').forEach(li=>{li.ondragstart=e=>{li.classList.add('dragging');e.dataTransfer.setData('text/plain',li.dataset.entryId)};li.ondragend=()=>li.classList.remove('dragging')});document.querySelectorAll('[data-day-card]').forEach(card=>{card.ondragover=e=>{e.preventDefault();card.classList.add('cashflow-drop-target')};card.ondragleave=()=>card.classList.remove('cashflow-drop-target');card.ondrop=e=>{e.preventDefault();card.classList.remove('cashflow-drop-target');const id=e.dataTransfer.getData('text/plain'),date=card.dataset.cashflowDate;if(id&&date)quick(id,'move',{date})}})}
  function render(){const cards=[...document.querySelectorAll('[data-day-card]')];if(!cards.length)return false;const start=new Date();start.setHours(0,0,0,0);cards.forEach((card,index)=>{const d=new Date(start);d.setDate(start.getDate()+index);const date=d.toISOString().slice(0,10);card.dataset.cashflowDate=date;const day=items.filter(x=>x.date===date),panel=card.querySelector("div[id^='day-panel-']"),body=panel?.querySelector('.day-body');if(!body)return;body.querySelectorAll('.cashflow-day-add,.cashflow-day-add-row').forEach(el=>el.remove());const row=document.createElement('div');row.className='cashflow-day-add-row';row.innerHTML='<button class="cashflow-day-add" type="button"><span>＋</span><span>הוספת תנועה</span></button>';row.querySelector('button').onclick=()=>create(date);body.prepend(row);const sections=body.querySelectorAll('section');['income','expense'].forEach((type,i)=>{const ul=sections[i]?.querySelector('ul'),rows=day.filter(x=>x.type===type);if(ul)ul.innerHTML=rows.length?rows.map(entry).join(''):'<li class="empty">אין תנועות</li>'});const small=card.querySelector('.summary-date small');if(small)small.textContent=`${day.length} תנועות`;});bind();return true;}
  async function load(){styles();modal();const{data,error}=await client.rpc('get_cashflow_entries_report');if(error){console.error(error);return}const report=data?.report||data||{};items=Array.isArray(report.items)?report.items:[];if(!render()){let n=0,t=setInterval(()=>{if(render()||++n>20)clearInterval(t)},250)}}
  window.addEventListener('load',()=>setTimeout(load,100));window.addEventListener('beautix:report-loaded',()=>setTimeout(load,50));setTimeout(load,150);
})();