window.BEAUTIX_TRANSLATIONS = {
  he: {
    meta: { name: 'עברית', dir: 'rtl', locale: 'he-IL' }
  },
  en: {
    meta: { name: 'English', dir: 'ltr', locale: 'en-US' },
    common: {
      'דשבורד':'Dashboard','ניתוחים מפורטים':'Detailed Analytics','שיווק והמרה':'Marketing & Conversion','רענון':'Refresh','יציאה':'Log out','התנתקות':'Log out','תפריט משתמש':'User menu','עריכת פרופיל':'Edit profile','שינוי סיסמה':'Change password','רענון התחברות':'Refresh session','שפה':'Language','עברית':'Hebrew','אנגלית':'English','פרטים':'Details','סגירת פרטים':'Close Details','פעולות':'Actions','שמירה':'Save','אישור':'Confirm','ביטול':'Cancel','סגירה':'Close','חיפוש':'Search','סינון':'Filter','הצג הכל':'Show All','אין נתונים':'No data','אין נתון':'No data','טוען נתונים...':'Loading data...','בודק הרשאת כניסה...':'Checking access permission...','רשומות':'records','רשומה':'record','יעד':'Target','בפועל':'Actual','תחזית':'Forecast','הערה':'Note','סטטוס':'Status','תאריך':'Date','סוג':'Type','סכום':'Amount','תיאור':'Description','לקוח':'Customer','לקוחות':'Customers','טלפון':'Phone','חיוג':'Call','אין טלפון':'No phone','שם':'Name','סה״כ':'Total','חודש':'Month','יום':'Day','ימים':'Days','שבוע':'Week','שבועות':'Weeks','חודשי':'Monthly','יומי':'Daily','שבועי':'Weekly'
    },
    auth: {
      'כניסה למערכת BeautiX':'Sign in to BeautiX','יש להתחבר לפני הצגת נתוני העסק.':'Please sign in to view business data.','אימייל':'Email','סיסמה':'Password','הצג סיסמה':'Show password','שכחתי סיסמה':'Forgot password','זכור אותי במכשיר הזה':'Remember me on this device','כניסה':'Sign in','איפוס סיסמה':'Reset password','נשלח קישור מאובטח לכתובת האימייל שלך.':'A secure link will be sent to your email.','שליחת קישור איפוס':'Send reset link','חזרה לכניסה':'Back to sign in','בחירת סיסמה חדשה':'Choose a new password','הזן סיסמה חדשה לחשבון שלך.':'Enter a new password for your account.','סיסמה חדשה':'New password','אימות סיסמה':'Confirm password','עדכון סיסמה':'Update password'
    },
    dashboard: {
      'סקירה ניהולית':'Management Overview','תמונת מצב מיידית':'Immediate Snapshot','מדדים מרכזיים, תובנה מובילה ויעדי בריאות עסקית':'Key metrics, leading insight and business health targets','ציון בריאות עסקית':'Business Health Score','תובנה מרכזית':'Primary Insight','סיכון מרכזי':'Primary Risk','איך לשפר את הציון':'How to Improve the Score','עמידה צפויה ביעד':'Forecast Target Achievement','החזר הלוואות חודשי':'Monthly Loan Repayments','יתרה חזויה ל-30 יום':'30-Day Forecast Balance','מכירות ויעדים':'Sales & Targets','מגמת מכירות חודשית':'Monthly Sales Trend','קצב שבועי':'Weekly Pace','שבוע מול שבוע':'Week over Week','התקדמות מול היעד':'Progress to Target','יעד פעיל':'Active Target','תקין / היעד הושג':'Healthy / Target Achieved','יעד פעיל':'Active Target','דורש תשומת לב':'Needs Attention','סיכון / חריגה':'Risk / Exception'
    },
    sales: {
      'מכירות':'Sales','ביצועים, יעדים ותחזית':'Performance, Targets & Forecast','מצב המכירות החודשי, קצב ההתקדמות והיעד הפעיל':'Monthly sales status, pace and active target','מכירות החודש':'Sales This Month','יעד מכירות חודשי':'Monthly Sales Target','קצב מכירות יומי':'Daily Sales Pace','תחזית סוף חודש':'Month-End Forecast','פער מהיעד':'Gap to Target','תקבולים מיידיים':'Immediate Receipts','נדרש לכל יום עבודה שנותר':'Required per Remaining Workday','התקדמות ליעד':'Progress to Target','מתחת ליעד':'Below Target','נותרו ליעד':'Remaining to Target','עסקאות':'Transactions','עסקה':'Transaction','מכירות שבועיות':'Weekly Sales','מספר עסקאות':'Transaction Count'
    },
    opportunities: {
      'הזדמנויות מכירה':'Sales Opportunities','מוצרים, לקוחות ופוטנציאל':'Products, Customers & Potential','חובות לקוחות':'Customer Debts','פוטנציאל גבייה מיידי לפי הנתון החודשי':'Immediate collection potential based on monthly data','מכירות שטרם הפכו לתקבול מיידי':'Sales Not Yet Collected','מוצרים / טיפולים מובילים':'Top Products / Treatments','לקוחות עם פוטנציאל חזרה':'Customers with Return Potential','נדרש חיבור ביקורים והיסטוריית לקוחות':'Visit and customer history connection required','פתיחת רשימה':'Open List','סגירת רשימה':'Close List','פוטנציאל מכירה':'Sales Potential','מכירות מצטברות':'Lifetime Sales','ביקור אחרון':'Last Visit','ימים מאז ביקור':'Days Since Visit','קביעת תור':'Set Appointment','נוצר קשר':'Contacted','אין מענה':'No Answer','לא רלוונטי':'Not Relevant','אבוד':'Lost','חדש':'New'
    },
    profitability: {
      'הכנסה ורווחיות':'Income & Profitability','תחזית הכנסה, יתרות בנק ורווחיות':'Income Forecast, Bank Balances & Profitability','נזילות, גבייה, רזרבות ויעדי רווח':'Liquidity, collections, reserves and profit targets','עו״ש עסקי':'Business Checking','פיקדון עסקי':'Business Deposit','יתרות מט״ח':'Foreign Currency Balances','זיכויים עתידיים':'Future Credits','יעד עו״ש':'Checking Target','רווח גולמי לאחר מסים':'Gross Profit After Taxes','שיעור מהמכירות':'Share of Sales','סה״כ לשמור לכל המסים החודש':'Total Tax Reserve This Month','מע״מ לאחר קיזוז + מס הכנסה משוער':'VAT after deductions + estimated income tax'
    },
    health: {
      'בריאות עסקית':'Business Health','הוצאות, מסים ותובנות תזרים':'Expenses, Taxes & Cash-Flow Insights','מדדים שמסבירים את איכות הפעילות ולא רק את המחזור':'Metrics that explain operating quality, not only revenue','הוצאות חודשיות':'Monthly Expenses','מע״מ עסקאות מדויק':'Exact Output VAT','מע״מ תשומות משוער':'Estimated Input VAT','מע״מ לאחר קיזוז':'VAT After Deductions','מס הכנסה משוער':'Estimated Income Tax','רזרבת מס כוללת':'Total Tax Reserve','מסים':'Taxes'
    },
    cashflow: {
      'תזרים':'Cash Flow','תחזית 30 יום':'30-Day Forecast','תנועות צפויות לפי המידע הקיים במערכת':'Expected transactions based on current system data','פתח הכל':'Expand All','סגור הכל':'Collapse All','הרחב הכל':'Expand All','כווץ הכל':'Collapse All','הכנסות צפויות':'Expected Income','הוצאות צפויות':'Expected Expenses','נטו צפוי':'Expected Net','תזרים נטו':'Net Cash Flow','יתרה חזויה בסוף התקופה':'Forecast Ending Balance','יום שפל חזוי':'Forecast Low Day','היום עם ההוצאה הגבוהה ביותר':'Largest Expense Day','יום ההוצאה הגדול ביותר':'Largest Expense Day','כיסוי התחייבויות':'Liability Coverage','כיסוי הכנסות מול הוצאות':'Income-to-Expense Coverage','הכנסות':'Income','הוצאות':'Expenses','נטו':'Net','יתרה חזויה':'Forecast Balance','אין תנועות':'No Transactions','הוספת תנועה':'Add Transaction','הוספת תנועה חדשה':'Add New Transaction','עדכון תנועה':'Update Transaction','הכנסה':'Income','הוצאה':'Expense','מתוכנן':'Planned','בוצע':'Completed','נדחה':'Deferred','באיחור':'Overdue','בוטל':'Cancelled','סמן בוצע':'Mark Completed','שכפול':'Duplicate','תנועה חוזרת':'Recurring Transaction','העבר תאריך':'Move Date','דחה למחר':'Defer to Tomorrow','צור תזכורת':'Create Reminder','עריכה מלאה':'Full Edit','תדירות':'Frequency','יומית':'Daily','שבועית':'Weekly','חודשית':'Monthly','מספר מופעים':'Number of Occurrences','תאריך יעד':'Target Date','מועד תזכורת':'Reminder Time','לבטל ולהסתיר את התנועה?':'Cancel and hide this transaction?','הפיכה לתנועה חוזרת':'Make Recurring','העברת התנועה לתאריך אחר':'Move Transaction','שכפול התנועה':'Duplicate Transaction','יצירת תזכורת':'Create Reminder','הוצאה צפויה':'Expected Expense','הכנסה צפויה':'Expected Income','חסר כיסוי מלא להוצאות הצפויות':'Expected expenses are not fully covered'
    },
    balance: {
      'מאזן':'Balance Sheet','הלוואות ונכסים':'Loans & Assets','התחייבויות ונכסים עסקיים לפי הנתונים הזמינים':'Business liabilities and assets based on available data','סך החוב הכולל':'Total Outstanding Debt','מספר הלוואות':'Number of Loans','החזר חודשי כולל':'Total Monthly Payment','ריבית חודשית כוללת':'Total Monthly Interest','קרן חודשית כוללת':'Total Monthly Principal','יתרה נוכחית':'Current Balance','סכום מקורי':'Original Amount','נפרע':'Repaid','נותר':'Remaining','תשלום חודשי':'Monthly Payment','ריבית חודשית':'Monthly Interest','קרן חודשית':'Monthly Principal','תאריך התחלה':'Start Date','תאריך סיום':'End Date','סטטוס תשלומים':'Payment Status','תשלומים שנותרו':'Payments Remaining','ריבית משתנה':'Variable Interest','ריבית קבועה':'Fixed Interest'
    },
    marketing: {
      'משפך שיווקי':'Marketing Funnel','מליד ללקוח משלם':'From Lead to Paying Customer','התאמה לפי מספר טלפון בין Meta, מאגר הלקוחות והיסטוריית המכירות.':'Phone-based matching between Meta, customer records and sales history.','לידים':'Leads','עם מספר טלפון':'with phone number','לידים שנמצאו כלקוחות':'Leads Matched to Customers','מהלידים':'of leads','הגיעו לביקור':'Visited','הפכו ללקוחות משלמים':'Became Paying Customers','הכנסה מיוחסת ללידים':'Lead-Attributed Revenue','לפי לקוחות תואמים והיסטוריית המכירות':'Based on matched customers and sales history','נמצאו כלקוחות אך לא ביקרו':'Matched Customers Who Never Visited','לקוחות וגבייה':'Customers & Collections','חובות, ביקורים ופגישות עתידיות':'Debts, Visits & Future Appointments','לקוחות במאגר':'Customers in Database','לקוחות שמעולם לא ביקרו':'Customers Who Never Visited','לקוחות עם פגישה עתידית':'Customers with Future Appointment','לקוחות בחוב':'Customers in Debt','קמפיינים':'Campaigns','ביצועים לפי קמפיין':'Performance by Campaign','קמפיין':'Campaign','משלמים':'Paying','חוב':'Debt','לקוחות עם יתרה שלילית':'Customers with Negative Balance','ביקורים':'Visits','מעקב מכירות':'Sales Follow-up','שם ליד':'Lead Name','שם לקוח':'Customer Name','תאריך ליד':'Lead Date','פגישה עתידית':'Future Appointment','עדכון ליד':'Update Lead','נקבע תור חדש':'New Appointment Set','הלקוחה כבר ביקרה':'Customer Already Visited','החזרה לחדש':'Reset to New','הערת מעקב':'Follow-up Note','תאריך תור':'Appointment Date'
    },
    whatsapp: {
      'WhatsApp':'WhatsApp','הודעת WhatsApp':'WhatsApp Message','יצירת הודעה':'Create Message','פתיחה ב-WhatsApp':'Open in WhatsApp','העתקת הודעה':'Copy Message','הודעה הועתקה':'Message Copied','חם ואישי':'Warm & Personal','קצר וישיר':'Short & Direct','רשמי':'Formal','סגנון':'Tone'
    }
  }
};
